services:
  workspace:
    container_name: workspace
    build:
      dockerfile: ./workspace/Dockerfile
      args:
        PROJECT_DIR: ${PROJECT_DIR}
        PHP_VERSION: ${PHP_VERSION:-8.2}
        APT_PACKAGES: ${APT_PACKAGES}
        DB_DRIVER: ${DB_DRIVER:-sqlite}
    ports:
      - "${APP_PORT:-80}:${APP_PORT:-80}"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    volumes:
      # Project File Mounts
      - ${PROJECT_DIR}:${CONTAINER_DEST:-/var/www/html}
      
      # Nginx Mounts
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount the custom NGINX configuration file
      # - ./default.conf:/etc/nginx/sites-available/default  # Mount the default site configuration
      - ./nginx/larabox.conf:/etc/nginx/conf.d/default.conf
      
      # Mount custom PHP configuration
      - ./php/larabox.ini:/usr/local/etc/php/conf.d/php.ini                 
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - larabox

  # MySQL Database Container.
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "${MYSQL_ROOT_HOST}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
      MYSQL_EXTRA_OPTIONS: "${MYSQL_EXTRA_OPTIONS}"
    volumes:
      - data:/var/lib/mysql
    networks:
      - larabox
    depends_on:
      - workspace

  # MailHog Container to test emails.
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    networks:
      - larabox
    depends_on:
      - workspace
networks:
  larabox:
    driver: bridge
volumes:
  data:
